[character]
success_symbol = "λ "
error_symbol = "λ "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[aws]
symbol = " "

[conda]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[elixir]
symbol = " "

[docker_context]
symbol = " "
only_with_files = true
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile', 'docker-compose.deployment.yml']
